### PR TITLE
Add NumberBox widget

### PR DESCRIPTION
**Pull request by WinXaito**
## Pre-launch Checklist

- [ ] I have run `dartfmt` on all changed files  
- [ ] I have updated `CHANGELOG.md` with my changes  
- [ ] I have run "optimize/organize imports" on all changed files
- [ ] I have addressed all analyzer warnings as best I could
- [ ] I have added/updated relevant documentation
- [ ] I have run `flutter pub publish --dry-run` and addressed any warnings

Compact mode:

numberbox_compact

Inline mode:

numberbox_inline

### CODE REVIEW

**Comment by bdlukaa** [comment]
When the controller value is changed, the text selection cursor should be changed to the end instead of being at the start

**Comment by WinXaito** [comment]
I really have no idea how to do it.

numberbox_compact

The overlay must be present, when textbox have focus (and when overlay is open, the focus must stay on textbox !) and textbox must be editable when overlay is open.

So, with the dropdown overlay solution, when the overlay is open the focus on textbox is lost and nothing stay editable...

**Comment by bdlukaa** [comment]
@WinXaito `IconButton` requests focus everytime the user pressed the button. You can create your own button that do not request focus. Also, you can use a `FocusNode` to request the focus back to the text box if it's by any mean lost

**Comment by ricardoboss** [comment]
@WinXaito are you planning on completing this?

**Comment by bdlukaa** [comment]
`EditableComboBox` may be similar to this

**Comment by WinXaito** [comment]
Closing in favor of #771

**Pull request closed without merging**
