### PR TITLE
Implement Lazy Tree View

### LINKED ISSUE #135: Lazy expansion of TreeView nodes
Firstly, this package is _fantastic_. What an incredible piece of work. So grateful for your work.

**Scenario**
I have a `TreeView` where it's computationally expensive to calculate the nodes. So what I want is a callback that I can use to lazily populate a node when it's opened. I've solved this temporarily by forking your code and adding an `onExpanded` callback. I've also added a non-visual `PlaceholderTreeViewItem` that ensures the node is expandable, and when the callback is fired, I check whether the child is a `PlaceholderTreeViewItem`. If so, I clear the children and populate at that point. 

The solution I have is workable, but you may well have a better one. 
https://github.com/timsneath/regedit/blob/main/lib/custom_tree_view_item.dart

Example usage:
https://github.com/timsneath/regedit/blob/main/lib/registry_tree_view.dart

### PR DESCRIPTION
**Pull request by bdlukaa**
Fixes #135 

Usage:

```dart

  late List<TreeViewItem> items;

  @override
  initState() {
    super.initState();
    items = [
      TreeViewItem(
        content: const Text('Work Documents'),
        lazy: true,
        onInvoked: (item) async {
          // if it's already populated, return
          if (item.children.isNotEmpty) return;
          // mark as loading
          setState(() => item.loading = true);
          // do your fetching...
          await Future.delayed(const Duration(seconds: 2));
          setState(() {
            item
              // set loading to false
              ..loading = false
              // add the fetched nodes
              ..children.addAll([
                TreeViewItem(content: const Text('XYZ Functional Spec')),
                TreeViewItem(content: const Text('Feature Schedule')),
                TreeViewItem(content: const Text('Overall Project Plan')),
                TreeViewItem(
                    content: const Text('Feature Resources Allocation')),
              ]);
          });
        },
        children: [],
      ),
      TreeViewItem(
        content: const Text('Personal Documents'),
        lazy: true,
        children: [
          TreeViewItem(
            content: const Text('Home Remodel'),
            children: [
              TreeViewItem(content: const Text('Contractor Contact Info')),
              TreeViewItem(content: const Text('Paint Color Scheme')),
              TreeViewItem(content: const Text('Flooring weedgrain type')),
              TreeViewItem(content: const Text('Kitchen cabinet style')),
            ],
          ),
        ],
      ),
    ];
  }

TreeView(
  items: items,
  onItemInvoked: (item) async => debugPrint('$item'),
),
```

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files  
- [x] I have updated `CHANGELOG.md` with my changes  
- [ ] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could
- [x] I have added/updated relevant documentation
- [ ] I have run `flutter pub publish --dry-run` and addressed any warnings

### CODE REVIEW

**Comment by timsneath** [comment]
Splendid! I wonder whether the loading state will flicker if the expansion only takes ~100ms? 

In my scenario, no individual node takes very long to populate, it's just that the entire tree is too large to load. I'll try this out and report back.

**Comment by bdlukaa** [comment]
> I wonder whether the loading state will flicker if the expansion only takes ~100ms?

Probably. The loading indicator can be customizable by providing `loadingWidget` on both `TreeView` and `TreeViewItem` if you wish a custom loading indicator!

**Comment by timsneath** [comment]
Ah, that probably solves my concern. Thanks!

**Comment by yepyeniceri** [comment]
When I tried this the "super.initState();" is being highlighted. I get the Errormessage "The method 'initState' isn't defined in a superclass of 'Testpage4'." 
Testpage4 is an alteration of the example file "tree_view.dart"
What might I do wrong?

**Comment by bdlukaa** [comment]
the example `tree_view` isn't a widget, thefore there isn't a `initState`. You must do that when initializing the list

**Pull request merged**
