### PR TITLE
Replace WindowButtons & Add Confirm before closing

### PR DESCRIPTION
**Pull request by lijy91**
## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files  
- [x] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could
- [x] I have added/updated relevant documentation
- [x] I have run `flutter pub publish --dry-run` and addressed any warnings

### CODE REVIEW

**Comment by WinXaito** [comment]
I think the prevent on close is not really useful (not a feature from fluent), and I don’t like when a software does nothing and want a confirmation for close.

**Comment by bdlukaa** [comment]
> I think the prevent on close is not really useful (not a feature from fluent), and I don’t like when a software does nothing and want a confirmation for close.

I wanted to add this a long time ago. I believe it's a good way to showcase the `ContentDialog` as well.

**Review by bdlukaa — APPROVED** [review]
LGTM!

**Pull request merged**
