### PR TITLE
Fix ISSUE: MenuFlyoutSubItem was not displaying when hovered or pressing over in a DropdownButton. 

### PR DESCRIPTION
**Pull request by Abbas1Hussein**
The error occurred because of the inheritance relationship between the **MenuFlyoutSubItem** class that extends from **MenuFlyoutItem**.

**before** ( _picture )1_:

``` dart
if (widget.closeAfterClick && item is MenuFlyoutItem);
```

**after** ( _picture 2_):

``` dart
if (item is MenuFlyoutSubItem) {
 return _buildMenuFlyoutISubItem(item);
}

if (widget.closeAfterClick && item is MenuFlyoutItem) {
 return _buildMenuFlyoutItem(item, context);
}

```

<table>
  <tr>
    <td>
      Issue
    </td>
    <td>
      After Fixed
    </td>
  </tr>
</table>

##  Checklist

- [x] I have updated `CHANGELOG.md` with my changes 
- [x] I have run "dart format ." on the project

### CODE REVIEW

**Comment by bdlukaa** [comment]
Could you explain the issue better? I don't understand it

**Comment by Abbas1Hussein** [comment]
> Could you explain the issue better? I don't understand it

**The Problem:**
the `MenuFlyoutSubItem` is not displaying when hovered or pressed.

```dart
return DropDownButton(
  title: const Text('menu'),
  items: [
    MenuFlyoutItem(
      text: const Text('import'),
      onPressed: () {},
    ),
    // MenuFlyoutSubItem items will not display when hovered or pressed.
    MenuFlyoutSubItem(
      text: const Text('open with...'),
      items: (context) {
        return [
          MenuFlyoutItem(text: const Text('powerpoint'), onPressed: () {}),
          MenuFlyoutItem(text: const Text('excel'), onPressed: () {}),
          MenuFlyoutItem(text: const Text('word'), onPressed: () {}),
        ];
      },
    ),
    MenuFlyoutItem(text: const Text('export'), onPressed: () {}),
  ],
);
```

Upon further reflection, I've identified an issue with the initial solution proposed in the pull request. 

and best solution it removing the `closeAfterClick` parmater, 
and closeing `MenuFlyoutItem`  automatically after a click.

**Revised Solution:**
-  Remove `closeAfterClick` and automatically close `MenuFlyoutItem` after a click.

I acknowledge that the initial solution might not have been entirely accurate, and I believe this revised approach provides a more effective resolution.

I'm open to any feedback you may have and am willing to make further adjustments if necessary.

**Comment by bdlukaa** [comment]
I like the first solution better. I'd like to keep the `closeAfterClick` property, since this is the case on the native side.

**Comment by Abbas1Hussein** [comment]
> I like the first solution better. I'd like to keep the `closeAfterClick` property, since this is the case on the native side.

the issue is related to the fact that only the first `MenuFlyoutSubItem` is displayed as expected, but subsequent ones are not showing correctly when hovered or pressed.

``` dart
return DropDownButton(
  title: const Text('menu'),
  items: [
    MenuFlyoutItem(
      text: const Text('import'),
      onPressed: () {},
    ),
    // MenuFlyoutSubItem items will display when hovered or pressed.
    MenuFlyoutSubItem(
      text: const Text('open with...'),
      items: (context) {
        return [
          MenuFlyoutItem(text: const Text('powerpoint'), onPressed: () {}),
          MenuFlyoutItem(text: const Text('excel'), onPressed: () {}),
          MenuFlyoutItem(text: const Text('word'), onPressed: () {}),
        ];
      },
    ),
    // Additional MenuFlyoutSubItem items will not display when hovered or pressed.
    MenuFlyoutSubItem(
      text: const Text('open with 2 ...'),
      items: (context) {
        return [
          MenuFlyoutItem(text: const Text('powerpoint 2'), onPressed: () {}),
          MenuFlyoutItem(text: const Text('excel 2'), onPressed: () {}),
          MenuFlyoutItem(text: const Text('word 2'), onPressed: () {}),
        ];
      },
    ),
    MenuFlyoutItem(text: const Text('export'), onPressed: () {}),
  ],
);

```

I will make another attempt to resolve the issue while retaining the `closeAfterClick` property.

**Comment by Abbas1Hussein** [comment]
Hello there, I've resolved all the issues, and now it works as expected.

**Review by bdlukaa — APPROVED** [review]

**Comment by bdlukaa** [comment]
Hello, the tests are not passing and you should rebase your branch.

**Comment by Abbas1Hussein** [comment]
> Hello, the tests are not passing and you should rebase your branch.

- dart format lib/src/controls/inputs/dropdown_button.dart
Formatted 1 file (0 changed) in 0.40 seconds.
 
- dart analyze
Analyzing fluent_ui... No issues found!

**Pull request merged**
