### PR TITLE
add build workflows

### PR DESCRIPTION
**Pull request by bdlukaa**
## Pre-launch Checklist

- [x] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "dart format ." on the project  
- [x] I have added/updated relevant documentation

### CODE REVIEW

**Comment by h3x4d3c1m4l** [comment]
lmk if you would like any help with macOS!

**Comment by bdlukaa** [comment]
I don't think it makes sense to have a build workflow for platforms other than windows

**Comment by h3x4d3c1m4l** [comment]
Well looking from "Microsoft perspective", it probably doesn't cause Fluent UI is designed for Windows. However, due to Flutter's nature being a multiplatform UI framework, it could make sense. There is nothing in `fluent_ui` that stops me from running my `fluent_ui` based apps on macOS. It even looks pretty nice too 😄 

On the other hand there are pretty good reasons you should indeed ignore other platforms:
- As of now you still need macOS to compile for macOS, and macOS minutes on GH Actions are expensive
-

**Comment by bdlukaa** [comment]
I ended up adding the build workflow for it, just for precaution.

> As of now you still need macOS to compile for macOS, and macOS minutes on GH Actions are expensive

They aren't charged on public repos

**Pull request merged**
