### PR TITLE
Add Persian

### PR DESCRIPTION
**Pull request by xmine64**
Adding Persian Localization

## Pre-launch Checklist

- [ ] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "dart format ." on the project  
- [ ] I have added/updated relevant documentation

### CODE REVIEW

**Review by bdlukaa — APPROVED** [review]

**Comment by xmine64** [comment]
when it'll make it to stable release? I tried to use fluent_ui in my app and it crashed just because there was no localization for Persian.

**Comment by bdlukaa** [comment]
@xmine64 weird! It shouldn't crash. can you file an issue about that crash?

I don't have any ETA for when it'll be published, but you can use the following for now:

```yaml
dependencies:
  fluent_ui:
    git: https://github.com/bdlukaa/fluent_ui.git
```

**Comment by xmine64** [comment]
> It shouldn't crash. can you file an issue about that crash?

It says it can't find `FluentLocalization`, while I had `DefaultFluentLocalication.delegate` in my localization delegates. It was ok when I changed my locale to English but my app was Persian-only and I got error for other parts of my app. I should open an issue?

> but you can use the following for now

Sure thanks.

**Comment by bdlukaa** [comment]
> I should open an issue?

It'd be cool to do so, so we can investigate the issue. Please post the error message

**Comment by xmine64** [comment]
Looks like I can't reproduce it in a simple project. in the last project my app was wrapped inside a BetterFeedback widget (https://github.com/ueman/feedback), I had added FluentLocalizationDelegate to its localization delegates too.

**Comment by henry2man** [comment]
https://github.com/bdlukaa/fluent_ui/issues/371

**Pull request merged**
