### PR TITLE
DateTimePicker update

### LINKED ISSUE #306: Date Picker - placeholder
More of a question than any particular bug. The documentation shows a placeholder for the date picker: **https://pub.dev/packages/fluent_ui#date-picker**

But me doing the same following the example :
```
// property.date is set to DateTime.now()
Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                  child: Padding(
                      padding: const EdgeInsets.only(left: 5),
                      child: DatePicker(
                        header: property.label,
                        onChanged: (v) => setState(() => property.date = v),
                        selected: property.date,
                      )))
            ]);
```
Gives me the current date with no placeholder. 
Since I can't set the selected value to null, is that screenshot/gif correct in the documentation?

**Screenshots**
Documentation placeholder screenshot:
image

### PR DESCRIPTION
**Pull request by bdlukaa**
Fixes #306

## Pre-launch Checklist

- [x] I have updated `CHANGELOG.md` with my changes  
- [x] I have run "dart format ." on the project  
- [x] I have added/updated relevant documentation

### CODE REVIEW

**Comment by bdlukaa** [comment]
The following translations were added

```json
"hour": "hour",
  "minute": "minute",
  "am": "AM",
  "pm": "PM",
  "month": "month",
  "day": "day",
  "year": "year"
```
@WinXaito @henry2man @raitonoberu @larsb24 @alexmercerind @zacksleo @dmakwt @xmine64 @patricknicolosi 
if you guys could send the translated version of these in your mother language, I'd be so grateful :)

They're basically used as a placeholder when the current selected date is not provided (`null`)

**Comment by alexmercerind** [comment]
```json
  "hour": "घंटा",
  "minute": "मिनट",
  "am": "AM",
  "pm": "PM",
  "month": "महीना",
  "day": "दिन",
  "year": "साल"
```

Thanks!

**Comment by patricknicolosi** [comment]
```dart
  "hour": "ore",
  "minute": "minuti",
  "am": "",
  "pm": "",
  "month": "mese",
  "day": "giorno",
  "year": "anno"
```

There is no translation for "PM" and "AM" because we use 24h format

**Comment by dmakwt** [comment]
```
  "hour": "ساعة",
  "minute": "دقيقة",
  "am": "AM",
  "pm": "PM",
  "month": "شهر",
  "day": "يوم",
  "year": "سنة"
```

**Comment by xmine64** [comment]
"FA"

```
"hour": "ساعت",
"minute": "دقیقه",
"am": "ق.ظ.",
"pm": "ب.ظ.",
"month": "ماه",
"day": "روز",
"year": "سال"
```

**Comment by henry2man** [comment]
Spanish localisation `ES`:

```json
  "hour": "hora",
  "minute": "minuto",
  "am": "AM",
  "pm": "PM",
  "month": "mes",
  "day": "día",
  "year": "año"
```

@bdlukaa Relative to hours and minutes, should we use plural literals instead of singular ones?

Just in case, in Latin languages Spanish we just need to add a final `s` to the literal if needlessly.

**Comment by henry2man** [comment]
Also, will 24h format be available? In Spanish is not usual to use the AM/PM format, so instead we use 24h one.

**Comment by bdlukaa** [comment]
@henry2man

> Relative to hours and minutes, should we use plural literals instead of singular ones?

Singular ones. The texts will be used here:




> Also, will 24h format be available? In Spanish is not usual to use the AM/PM format, so instead we use 24h one.

It has been available since DateTime pickers were implemented.



Check the example app to play with it!

**Comment by WinXaito** [comment]
FR

```json
  "hour": "heure",
  "minute": "minute",
  "am": "AM",
  "pm": "PM",
  "month": "mois",
  "day": "jour",
  "year": "année"
```

Note: `AM` and `PM` are not used in french, we use 24h format. Translation for `AM/PM` can be `matin/après-midi`, but I think it's preferable to keep AM/PM.

And the date in french is in format : `DAY / MONTH / YEAR`, so Day must be before month ;)

**Pull request merged**
